option architecture-type code 93 = unsigned integer 16;

#include "/etc/dhcp/conf.d/dhcp-node0.conf";
#include "/etc/dhcp/conf.d/dhcp-node1.conf";
#include "/etc/dhcp/conf.d/dhcp-node2.conf";
#include "/etc/dhcp/conf.d/dhcpd_ztp.conf";
include "/etc/dhcp/conf.d/dhcp-scope.conf";
